### ISSUE TITLE
reorganize into subpackages

### ISSUE THREAD

**Issue by sahilpatelsp** [google/qhbm-library#99]
It might be worth considering reorganizing the library into collective subpackages rather than modules consisting of single files, which is the current approach. One such organization scheme could be the following:

    qhbmlib/
      __init__.py

      ebm/
            __init__.py
            ebm.py
            energy_functions/
                kobe.py
                mlp.py
                ...
            energy_samplers/
                energy_sampler.py
                mcmc/
                    mcmc.py
                    energy_kernel.py
                    mh.py
                    gwg.py
                    ...

        qnn/
            __init__.py
            qnn.py
            pqc/
                hea.py
                qcnn.py
                ...

        qhbm/
            __init__.py
            qhbm.py

        losses/
            __init__.py
            vqt.py
            qmhl.py
            ...
    
        metrics/
            __init__.py
            fidelity.py
            ...
    
        datasets/
            __init__.py
            hamiltonian.py
            ...
    
        utils/
            __init__.py
            utils.py

**Comment by zaqqwerty** [comment]
Resolved by #196
